version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - binary: huskybc
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    dir: .
    hooks:
      post:
        # Move binaries to npm-package/bin folder after compilation
        - cmd: mv {{ .Path }} npm-package/bin/{{ .Binary }}-{{ .Os }}{{ if eq .Os "windows" }}.exe{{ end }}
          dir: .

# Specify the main output folder
dist: npm-package/bin

# Disable default packing to use our own structure
archives:
  - format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"