version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - binary: huskybc-{{ .Os }}-{{ .Arch }}

    goos:
      - windows
      - darwin
      - linux

    goarch:
      - amd64
      - arm64

    ldflags:
      - -s -w

    gcflags:
      - -trimpath

    env:
      - CGO_ENABLED=0

    no_unique_dist_dir: true

# Avoid creating compressed files
archives:
  - formats: ["binary"]

# Specify the main output folder
dist: npm-package/bin

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
